#!/bin/bash
#
#   makeCrudeFiles - This file is part of cpd - The Copy Daemon
#
#   Copyright (C) 2017 loh.tar@googlemail.com
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#   MA 02110-1301, USA.

cd $(dirname $(readlink -e $0 ))

needSpace="1000" # Size is not fixed, in 1k blocks, ask du -kc ...
source ./test-config+lib.sh "$@"

i="0"
makeFile() {
  # Parms: crudeName prefix
  let i+=1
  tameName="$1"
  tameName="${tameName//\\[nrt]/" "}"
  printf -v crudeName "%bfile$i-%b" "$2" "$1"
  echo "Create crude file-$i-$tameName"
  sort -R ../cpd | head -n $(($RANDOM % 1400 +100)) > "$fileDir/$crudeName"
}

makeFile "with fishes ><((((*>  <°}}}c<"
makeFile "\nwith\nnewlines"
makeFile "\twith\ttabs"
makeFile " with spaces all around " " "
makeFile "starts-and-ends-with-newlines\n" "\n"
makeFile "starts-and-ends-with-tabs\t" "\t"
makeFile "with special chars !\"§$%&()=?\`+~\'#<>,;^°"

finishCreation
