#!/bin/bash
#
#   simulation - This file is part of cpd - The Copy Daemon
#
#   Copyright (C) 2017 loh.tar@googlemail.com
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#   MA 02110-1301, USA.

type=${1:-"small"}
extra="$2"
if [[ ! "small medium" =~ "$type" ]] ; then
  echo "Unknown simulation config: $type"
  exit 1
fi

cd $(dirname $(readlink -e $0 ))

source ./test-config+lib.sh "only-config"

cpdUserDir="$cpdDir/user-$(id -un)"

if [[ ! -d "$testDataDir/fakeData/$type/" ]] ; then
  ./makeFakeData "force"
fi


prepareTest() {
  echo "Prepare test with clean tmp dir"
  rm -rf "$cpdUserDir"
  mkdir -p "$cpdUserDir"
  touch  "$cpdUserDir/not-locked"

  cp "$testDataDir/fakeData/$type/"* "$cpdUserDir/"

  if [[ -n "$extra" ]] ; then
    echo "Test data set '$type' copied ready to use"
    exit
  fi
}

cd ..

if [[ -f $cpdUserDir/daemon-pid ]] ; then
  echo "There is a running daemon - will expel the beast"
  if ./cpd exit ; then
    echo "Puh, Good!"
  else
    echo "Um? Well, I ignore this in the hope that you know what you are doing"
    # Just to be sure all are gone
    sleep 1
    killall cpd 2>/dev/null
  fi
  prepareTest
  optWatch="1"
  echo "Read quick!"
  echo "Restart the daemon in simulation mode..."
  (sleep 6; ./cpd -s start 2>/dev/null 1>&2 )&
else
  prepareTest
fi

runUser() {
  echo "User $@" >> "$cpdUserDir/test.log"
  "$@" >> "$cpdUserDir/test.log" 2>&1
}

runCommand() {
  echo
  echo "Run: $@" | tee -a "$cpdUserDir/test.log"
  "$@" | tee -a "$cpdUserDir/test.log"
}

(
  runUser sleep 1
  runUser ./cpd s 2
  runUser ./cpd K 5
  runUser sleep 2
  runUser ./cpd r 2 5
)&

if (( optWatch )) ; then
  # No runCommand now, not working somehow, guess due tee
  echo "Run 'watch -n1 ./cpd show' for your interest"
  sleep 3
  watch -n1 ./cpd show
  # After Ctrl-C watch the info is gone, so bring it back
  runCommand ./cpd show
else
  runCommand ./cpd show
  runCommand ./cpd -s process
  runCommand ./cpd show e
fi

cd $OLDPWD
echo "Logfile of this test? Try: cat $cpdUserDir/test.log"
