#!/bin/bash

type=${1:-"small"}
cpdDir="/tmp/cpd/user-$(id -un)"

prepareTest() {
  echo "Prepare test with clean tmp dir"
  rm -rf $cpdDir/
  mkdir -p $cpdDir/
  cp ./testData/$type/{jobs,next-id,not-locked,job-files-*} $cpdDir/
}

if [[ -f $cpdDir/daemon-pid ]] ; then
  echo "There is a running daemon - will expel the beast"
  if ./cpd exit ; then
    echo "Puh, Good!"
  else
    echo "Um? Well, I ignore this in the hope that you know what you are doing"
    # Just to be sure all are gone
    sleep 1
    killall cpd
  fi
  prepareTest
  optWatch="1"
#   echo "Read quick! Ctrl-C to stop watching"
#   sleep 1
  ./cpd -s start
else
  prepareTest
fi

runUser() {
  echo "User $@" >> "$cpdDir/test.log"
  "$@" >> "$cpdDir/test.log" 2>&1
}

runCommand() {
  echo
  echo "Run: $@" | tee -a "$cpdDir/test.log"
  "$@" | tee -a "$cpdDir/test.log"
}

(
  runUser sleep 1
  runUser ./cpd K 5
  runUser ./cpd s 4 6 3
  runUser sleep 1
  runUser ./cpd K 5 6
  runUser sleep 2
  runUser ./cpd r 4 6 3
)&

if (( optWatch )) ; then
  watch -n1 ./cpd show
  # After Ctrl-C watch the info is gone, so bring it back
  runCommand ./cpd show
else
  runCommand ./cpd show
  runCommand ./cpd -s process
  runCommand ./cpd show e
fi

echo "Logfile of this test? Try: cat $cpdDir/test.log"
